# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    steps:
      - checkout
      - run:
        name: yarn install
        command: yarn install
      - run:
        name: yarn test
        command: yarn test